In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [3]:
##1. creating arrays 

In [5]:
list1 =[1,2,3,4]
print(list1)

[1, 2, 3, 4]


In [6]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3 4]


In [9]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [10]:
list1 =[1,2,3,4]
list2 =[11,22,33,44]
print(list1,list2)

[1, 2, 3, 4] [11, 22, 33, 44]


In [14]:
list1 =[1,2,3,4]
list2 =[11,22,33,44]
arr_list1_list2=np.array([list1,list2])
print(arr_list1_list2)

[[ 1  2  3  4]
 [11 22 33 44]]


In [16]:
list1 =[1,2,3,4]
list2 =[11,22,33,44]
list3=[12,13,14,15]
arr_list1_list2_list3=np.array([[list1,list2,list3]])
print(arr_list1_list2_list3)

[[[ 1  2  3  4]
  [11 22 33 44]
  [12 13 14 15]]]


In [17]:
print(arr_list1_list2_list3.ndim)

3


In [19]:
print(arr_list1_list2.ndim)

2


In [20]:
## 2. numpy array attributes

In [21]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)
print("ndim",arr1.ndim)

shape (2, 4)
size 8
dtype int64
ndim 2


In [23]:
#creat 2 array-1D and 3D, and find it's attributes

In [28]:
arr1 = np.array([[1.1,2.3,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)
print("ndim",arr1.ndim)

shape (2, 4)
size 8
dtype int64
ndim 2


In [30]:
# 3 . arrays intialized method


In [31]:
#zero array 
zero_arr =np.zeros((2,3))
print(zero_arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
#one array 
one_arr =np.ones((2,3))
print(one_arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
#one array 
one_arr =np.ones((3,3))
print(one_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
#full array
full_arr =np.full((3,2),8)
print (full_arr)

[[8 8]
 [8 8]
 [8 8]]


In [39]:
# identity matrix
id_arr=np.eye(4)
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
# impty array
print(np.empty(2))

[5.43230922e-312 7.29112202e-304]


In [47]:
#evenly spaced array
print (np.arange(1,10,2))

[1 3 5 7 9]


In [52]:
# spacific number of equally(spaced) values between a range

print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [54]:
#random values array- float
r_arr=np.random.rand(3,2)
print(r_arr)


[[0.53803105 0.79780452]
 [0.06991971 0.66995145]
 [0.50911827 0.32070879]]


In [56]:
#random values array- int
rint_arr=np.random.randint(1,10,(3,3))
print(rint_arr)


[[1 5 8]
 [3 8 8]
 [3 4 4]]


In [57]:
#array indexing and slicing

In [59]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [63]:
#find the indexing
print(a[4])

5


In [64]:
#find the indexing
print(a[3])

4


In [65]:
#find the indexing
print(a[-1])

5


In [71]:
#slicing: start stop start

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [72]:
print (a[0:4])

#stop values- index that is not included in output

[1 2 3 4]


In [73]:
print (a[-1:])

[5]


In [75]:
#jump
print(a[0:4:2])

[1 3]


In [77]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [81]:
print (arr2[1])

[4 5 6]


In [85]:
print (arr2[1][0])# frist in 0th values is 4

4


In [87]:
arr3 = np. array([[1,2,3],[4,5,6],[7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:

print (arr3[0])

print (arr3[1])
print (arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [92]:

print (arr3[0][2])
print (arr3[2][2])


3
9


In [95]:
print (arr3[:,2])#second column values

[3 6 9]


In [97]:
print (arr3[:,0])#1st column values
print (arr3[:,2])#2nd column values

[1 4 7]
[3 6 9]


In [98]:
#jump values
print(arr3[::2,0])

[1 7]
