In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [3]:
##1. creating arrays 

In [5]:
list1 =[1,2,3,4]
print(list1)

[1, 2, 3, 4]


In [6]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3 4]


In [9]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [10]:
list1 =[1,2,3,4]
list2 =[11,22,33,44]
print(list1,list2)

[1, 2, 3, 4] [11, 22, 33, 44]


In [10]:
list1 =[1,2,3,4]
list2 =[11,22,33,44]
arr_list1_list2=np.array([list1,list2])
print(arr_list1_list2)

[[ 1  2  3  4]
 [11 22 33 44]]


In [11]:
list1 =[1,2,3,4]
list2 =[11,22,33,44]
list3=[12,13,14,15]
arr_list1_list2_list3=np.array([[list1,list2,list3]])
print(arr_list1_list2_list3)

[[[ 1  2  3  4]
  [11 22 33 44]
  [12 13 14 15]]]


In [17]:
print(arr_list1_list2_list3.ndim)

3


In [19]:
print(arr_list1_list2.ndim)

2


In [20]:
## 2. numpy array attributes

In [21]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)
print("ndim",arr1.ndim)

shape (2, 4)
size 8
dtype int64
ndim 2


In [23]:
#creat 2 array-1D and 3D, and find it's attributes

In [28]:
arr1 = np.array([[1.1,2.3,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)
print("ndim",arr1.ndim)

shape (2, 4)
size 8
dtype int64
ndim 2


In [30]:
# 3 . arrays intialized method


In [31]:
#zero array 
zero_arr =np.zeros((2,3))
print(zero_arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
#one array 
one_arr =np.ones((2,3))
print(one_arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
#one array 
one_arr =np.ones((3,3))
print(one_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
#full array
full_arr =np.full((3,2),8)
print (full_arr)

[[8 8]
 [8 8]
 [8 8]]


In [39]:
# identity matrix
id_arr=np.eye(4)
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
# impty array
print(np.empty(2))

[5.43230922e-312 7.29112202e-304]


In [47]:
#evenly spaced array
print (np.arange(1,10,2))

[1 3 5 7 9]


In [52]:
# spacific number of equally(spaced) values between a range

print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [54]:
#random values array- float
r_arr=np.random.rand(3,2)
print(r_arr)


[[0.53803105 0.79780452]
 [0.06991971 0.66995145]
 [0.50911827 0.32070879]]


In [56]:
#random values array- int
rint_arr=np.random.randint(1,10,(3,3))
print(rint_arr)


[[1 5 8]
 [3 8 8]
 [3 4 4]]


In [57]:
#array indexing and slicing

In [59]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [63]:
#find the indexing
print(a[4])

5


In [64]:
#find the indexing
print(a[3])

4


In [65]:
#find the indexing
print(a[-1])

5


In [71]:
#slicing: start stop start

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [72]:
print (a[0:4])

#stop values- index that is not included in output

[1 2 3 4]


In [73]:
print (a[-1:])

[5]


In [75]:
#jump
print(a[0:4:2])

[1 3]


In [77]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [81]:
print (arr2[1])

[4 5 6]


In [85]:
print (arr2[1][0])# frist in 0th values is 4

4


In [87]:
arr3 = np. array([[1,2,3],[4,5,6],[7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:

print (arr3[0])

print (arr3[1])
print (arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [92]:

print (arr3[0][2])
print (arr3[2][2])


3
9


In [95]:
print (arr3[:,2])#second column values

[3 6 9]


In [97]:
print (arr3[:,0])#1st column values
print (arr3[:,2])#2nd column values

[1 4 7]
[3 6 9]


In [57]:
arr3 = np. array([[1,2,3],[4,5,6],[7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np

In [6]:
arr3 = np. array([[1,2,3],[4,5,6],[7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr3 = np. array([[1,2,3],[4,5,6],[7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(arr3[::,1:2])
print(arr3[2::,1:2])

[[2]
 [5]
 [8]]
[[8]]


In [9]:
# 5 array reashaping and flattening

In [16]:
arr1 = np.array ([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [17]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [18]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [20]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [22]:
# 6 array stacking and splitting

In [29]:
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [31]:
#splitting
c= np.array([[1,2,3],[4,5,6]])
print (c)

[[1 2 3]
 [4 5 6]]


In [37]:

hsplit=np.hsplit(c,3)
for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [39]:

vsplit=np.vsplit(c,2)
for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [40]:
# 7 mathematical opretions on array

In [42]:
a = np.array([1,2,3,4,-3])
print(a)

[ 1  2  3  4 -3]


In [43]:
print (a+10)
print(a-4)
print(a*2)
print(a/4)

[11 12 13 14  7]
[-3 -2 -1  0 -7]
[ 2  4  6  8 -6]
[ 0.25  0.5   0.75  1.   -0.75]


In [46]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [47]:
# 7 mathematical opretions on array

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [48]:
b= np.array([1,4,9])
print(b)

[1 4 9]


In [53]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [56]:
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))

[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]


In [58]:
# 8 mathematical opretions on multiple array

In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [61]:
print(np.add(a,b))

[ 6  8 10 12]


In [62]:
print (a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [64]:
# dot product
print(np.dot(a,b))

70


In [67]:
 #transpose
print(a.T)

[1 2 3 4]


In [72]:
t= np.array([[1,2,3],
            [5,6,7,]])
print(t)
print(t.T)

[[1 2 3]
 [5 6 7]]
[[1 5]
 [2 6]
 [3 7]]


In [ ]:
# 9 statistical funtion

In [75]:
a= np.array([[1,2,3],
            [5,6,7,]])
print(a)

[[1 2 3]
 [5 6 7]]


In [78]:
print (np.sum(a))

24


In [82]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

4.0
4.0
2.160246899469287
1
7


In [ ]:
# array camparison

In [85]:
a = np.array([1,2,3,4])
b = np.array([5,6,3,8])
print(a)
print(b)

[1 2 3 4]
[5 6 3 8]


In [86]:
print (a==b)
print(np.array_equal(a,b))

[False False  True False]
False


In [ ]:
#11 broadcasting

In [89]:
a= np.array([1,2,3,4])
b= np.array([5])
print(a+b)

[6 7 8 9]


In [90]:
c= np.array([[1,2,3],[4,5,6]])
d= np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [ ]:
# handling with nan and inf

In [93]:
data1= np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [94]:
print(np.isnan(data1))

[False False  True False False]


In [95]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [96]:
# save and load arrays

In [98]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [99]:
loaded_arr= np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]
